project:
  stages:
    - dev
    - prod
  root_dir: '/home/dennis/projects/tagebuch/'
  license:
    generate: true
    template_sub_folder: licenses
    file: 'apache_2_0.jinja2'
    params:
      year: now
      owner: dvk-net
  gitignore:
    generate: true
    template_sub_folder: gitignore
    file: 'python_gitignore.jinja2'
    params:
      - _project
      - local_settings.py # to ignore locals
      - storage/  # dev local storage
  readme:
    generate: true
    template_sub_folder: readme
    file: 'default.jinja2'
    params:
      READ_ME_TITLE: "test title"
  django:
    generate: true
    template_sub_folder: django
    project_folder_name: django # default is django. Folder within project_root
    project_src_folder_name: src # django project's root folder (with manage.py)
    packages:
      - Django
      - djangorestframework
      - markdown
      - django-filter
    docker:
      dev:
        generate: true
        template_sub_folder: django
        file: 'Dockerfile.jinja2'
        params:
          python_version: 3.12 # FROM python:{{ python_version }}
          django_dev_server_port: 8000
  compose:
    dev:
      generate: true
      template_sub_folder: compose
      file: 'compose.jinja2'
      params:
        HOST_PORT: 8081
        CONTAINER_PORT: 8080
        STAGE: dev