FROM python:{{ params.python_version }}
RUN apt-get update -y
RUN apt-get upgrade -y

WORKDIR /app

COPY ./requirements.txt ./
RUN pip install -r requirements.txt
COPY ./src ./src

CMD [ "python3", "./src/manage.py", "runserver", "0.0.0.0:{{ params.django_dev_server_port }}"]